### ISSUE TITLE
Cannot route to the demo

### ISSUE THREAD

**Issue by otengkwame** [michalsn/codeigniter-htmx-demo#14]
After a successful installation I cannot get to the demo route

On http://localhost:8080/demo

The page displays this text "
Whoops!
We seem to have hit a snag. Please try again later...
"

What can the issue be?

**Comment by michalsn** [comment]
I'm not sure what "successful installation" means, but try changing `CI_ENVIRONMENT` to `development`, you will see more detailed information.

I ran the demo with `php spark serve` and had no problems.

**Comment by datamweb** [comment]
>but try changing `CI_ENVIRONMENT` to `development`, you will see more detailed information.

```console
php spark  env development
```

**Comment by michalsn** [comment]
Lack of feedback.
