### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by athsx** [michalsn/codeigniter-htmx-demo#18]
I've done database things, but I try to use nginx, php-fpm to run the `project/public`, but it seems not to work, how should I run the demo?

**Comment by michalsn** [comment]
"... it seems not to work" is a rather broad term. One that basically says nothing 😅 
Are you able to run a clean CodeIgniter project (and see the welcome page)?

I can't help you with configuring your environment (if that's the problem), but you can always try running the command: 
```
php spark serve
``` 
this will start the PHP built-in server.

**Comment by athsx** [comment]
yes, I run a clean CI project, I ran `php spark serve` , but I have no idea where to access HTMX demo page

**Comment by michalsn** [comment]
> The default route to the demo page is `demo`.

If your development server started on http://localhost:8080 then running http://localhost:8080/demo should do the trick.

**Comment by athsx** [comment]
works, thank you
