### ISSUE TITLE
Call to undefined method CodeIgniter\HTTP\IncomingRequest::isHtmx() 

### ISSUE THREAD

**Issue by SpectraX07** [michalsn/codeigniter-htmx-demo#7]
have done whatever was suggested for the demo 
public $psr4 = [
        APP_NAMESPACE => APPPATH, // For custom app namespace
        'Config'      => APPPATH . 'Config',
        'Michalsn\CodeIgniterHtmxDemo' => APPPATH . 'ThirdParty/htmx-demo/src',
    ];
but still getting that error, do I have to load anything else?

**Comment by michalsn** [comment]
Have you installed the library itself?
```
composer require michalsn/codeigniter-htmx
```

**Comment by SpectraX07** [comment]
nah manual installation, as mentioned in doc.

**Comment by michalsn** [comment]
What is your CodeIgniter version?

**Comment by SpectraX07** [comment]
I got it thanks, but the doc is a bit confusing right, On the Manual installation section it's not even mentioned I have to run composer syntax in order to run the demo. 

It's working now

**Comment by michalsn** [comment]
Okay, thank you. I will try to update the introduction to be more clear about it.
